name: par2cmdline release build

on:
  push:
    branches:
    - 'master'

jobs:
  build-check-linux:
    uses: ./.github/workflows/build-check-linux.yml

  build-check-windows:
    uses: ./.github/workflows/build-check-windows.yml

  build-check-macos:
    uses: ./.github/workflows/build-check-macos.yml

  build-check-freebsd:
    uses: ./.github/workflows/build-check-freebsd.yml

  build-linux:
    needs:
    - build-check-linux

    name: build-linux (${{ matrix.arch }})

    strategy:
      matrix:
        include:
        - arch: amd64
          configure_host:
          xcc:
        - arch: arm64
          configure_host: --host=aarch64-linux-gnu
          xcc: aarch64-linux-gnu-
        - arch: armhf
          configure_host: --host=armv7l-linux-gnueabihf
          xcc: arm-linux-gnueabihf-

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cyberjunk/gha-ubuntu-cross@v5
      with:
        arch: ${{ matrix.arch }}

    - name: Build
      env:
        CC: ${{ matrix.xcc }}gcc
        CXX: ${{ matrix.xcc }}g++
        LDFLAGS: -static -s
      run: |
        ./automake.sh
        ./configure ${{ matrix.configure_host }}
        make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-linux-${{ matrix.arch }}
        path: |
          par2
        retention-days: 5

  build-windows:
    needs:
    - build-check-windows

    name: build-windows (${{ matrix.name }})

    strategy:
      matrix:
        include:
        - platform: x64
          name: x64
        - platform: ARM64
          name: arm64

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild -property:Configuration=Release -property:Platform=${{ matrix.platform }} par2cmdline.sln

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-win-${{ matrix.name }}
        path: |
          ${{ matrix.platform }}/Release/par2.exe
        retention-days: 5

  build-macos:
    needs:
    - build-check-macos

    name: build-macos (${{ matrix.arch }})

    strategy:
      matrix:
        include:
        - arch: amd64
          xcxxflags: -arch x86_64 -mmacosx-version-min=10.13
          configure_host: --host=x86_64-apple-darwin
        - arch: arm64
          xcxxflags: -mmacosx-version-min=11.0
        - arch: universal
          xcxxflags: -arch x86_64 -arch arm64 -mmacosx-version-min=10.13

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: prepare
      run: brew install automake

    - name: Build
      env:
        CXXFLAGS: ${{ matrix.xcxxflags }}
      run: |
        ./automake.sh
        ./configure ${{ matrix.configure_host }}
        make
        strip par2

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-macos-${{ matrix.arch }}
        path: |
          par2
        retention-days: 5

  build-freebsd:
    needs:
    - build-check-freebsd

    name: build-freebsd (${{ matrix.arch }})

    strategy:
      matrix:
        include:
        - arch: x86-64
          artifact_arch: amd64
        - arch: arm64
          artifact_arch: aarch64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build on FreeBSD
      uses: cross-platform-actions/action@v0.32.0
      env:
        LDFLAGS: -static -s
      with:
        operating_system: freebsd
        version: '15.0'
        architecture: ${{ matrix.arch }}
        environment_variables: LDFLAGS
        shell: sh
        run: |
          sudo pkg install -y autoconf automake libtool
          ./automake.sh
          ./configure
          make
          strip par2

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: par2cmdline-freebsd-${{ matrix.artifact_arch }}
        path: |
          par2
        retention-days: 5
