name: par2cmdline push build

on:
  push:
    branches:
    - '**'
    - '!master'

jobs:
  build-check-linux:
    uses: ./.github/workflows/build-check-linux.yml

  build-check-windows:
    uses: ./.github/workflows/build-check-windows.yml

  build-check-macos:
    uses: ./.github/workflows/build-check-macos.yml

